### ISSUE TITLE
Getting panic: the Client has not yet connected to the Server

### ISSUE THREAD

**Issue by DieterKoblenz** [hassio-addons/addon-happy-bubbles#8]
# Problem/Motivation

I installed the add-on via hass.io webinterface. I configured the settings and pressed "start"

## Expected behavior

Happy Bubbles to start..

## Actual behavior

Log:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: Happy Bubbles
 Presence detection server for Happy Bubbles Bluetooth beacon-based presence detection system.
-----------------------------------------------------------
 Add-on version: 3.0.5
 You are running the latest version of this add-on.
 System: HassOS 3.8  (armv7 / raspberrypi2)
 Home Assistant version: 0.103.6
 Supervisor version: 195
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[19:10:32] INFO: Starting Happy Bubbles Presence server...
EOF
panic: the Client has not yet connected to the Server
goroutine 1 [running]:
main.main()
	/code/happy-bubbles/presence-gh/main.go:766 +0x68c
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

## Steps to reproduce

Clean install. Install MQTT. Install Conbee. 
Then install Happy Bubbles, and start to run.

## Proposed changes

Don't have a fix, unfortunately.

**Comment by sinclairpaul** [comment]
Looks to be failing to subscribe/connect to MQTT, can your user specified connect to the MQTT topic?

**Comment by DieterKoblenz** [comment]
I've tested the same client id with MQTT.fx and it connects to the server and subscribes to the topic without a problem. 

I changed the logging to debug, but it doesn't give more information than that. I'm using an external mosquitto MQTT server. The "normal" MQTT interface of HASS works with it.

**Comment by DieterKoblenz** [comment]
Alright, I've changed the IP adress to the host name and now it works. 

Option: mqtt_host
The hostname or IP of the MQTT server to connect to.

So it should support the IP address.

**Comment by sinclairpaul** [comment]
In all honesty I'm not sure how we can help here from an add on perspective.  It is wrapping the original source application, which from my understanding is not maintained.  The library used by the application for the MQTT also doesn't seem to be maintained either.

My only thoughts is that the issue may be around the MQTT version of your broker and the support in the application.  Either way there isn't really anything that can be done from the add on itself.

**Comment by DieterKoblenz** [comment]
Weird, I've tried several variations including in the end ditching my standalone mosquitto server and using the HASS.IO one, and this does work. I'll close this issue for now, assuming it's indeed a library problem.
